const { test, expect } = require('@playwright/test');

test('Check Rallly homepage title', async ({ page }) => {
  await page.goto('http://localhost:3000');
  await expect(page).toHaveTitle("Home");
});

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('navigation').getByRole('link', { name: 'Create' }).click();
  await expect(page.getByText('EventDescribe what your event')).toBeVisible();
  await page.getByPlaceholder('Monthly Meetup').click();
  await page.getByPlaceholder('Monthly Meetup').fill('Monthly Meeting');
  await page.getByPlaceholder('Joe\'s Coffee Shop').click();
  await page.getByPlaceholder('Joe\'s Coffee Shop').fill('Steve\'s Coffee Shop');
  await page.getByPlaceholder('Hey everyone, please choose').click();
  await page.getByPlaceholder('Hey everyone, please choose').fill('Hello, please choose dates that work for you!');
  await page.getByRole('button', { name: 'Today' }).click();
  await page.getByRole('button', { name: 'Create poll' }).click();
  await page.getByRole('button', { name: 'Today' }).click();
  await page.getByRole('button', { name: 'Today' }).click();
  await page.getByRole('button', { name: 'Today' }).click();
  await page.getByPlaceholder('Hey everyone, please choose').click();
  await page.getByRole('button', { name: 'Today' }).click();
  await page.getByRole('tab', { name: 'Week view' }).click();
  await page.getByRole('button', { name: 'Today' }).click();
  await page.getByRole('tab', { name: 'Month view' }).click();
  await page.getByRole('button', { name: '18' }).click();
  await page.getByRole('button', { name: 'Today' }).click();
  await page.getByText('18').nth(1).click();
  await page.getByRole('button', { name: '19' }).click();
  await page.getByText('19').nth(1).click();
  await page.getByText('18').nth(1).click();
  await page.getByText('19').nth(1).click();
  await page.getByText('Jan').nth(2).click();
  await page.getByRole('button', { name: 'Today' }).click();
  await page.getByRole('button', { name: '18' }).click();
  await page.getByRole('button', { name: 'Create poll' }).click();
  await page.getByRole('button', { name: 'Create poll' }).click();
  await page.getByRole('button', { name: 'localhost:3000/invite/' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await expect(page.getByRole('heading', { name: 'Participants' })).toBeVisible();
  await page.getByTestId('add-participant-button').click();
  await page.getByTestId('vote-selector').click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByPlaceholder('Jessie Smith').click();
  await page.getByPlaceholder('Jessie Smith').fill('Steve');
  await page.getByPlaceholder('jessie.smith@example.com').click();
  await page.getByPlaceholder('jessie.smith@example.com').fill('steve-test@gmail.com');
  await page.getByPlaceholder('jessie.smith@example.com').press('ArrowLeft');
  await page.getByPlaceholder('jessie.smith@example.com').press('ArrowLeft');
  await page.getByPlaceholder('jessie.smith@example.com').press('ArrowRight');
  await page.getByPlaceholder('jessie.smith@example.com').press('ArrowLeft');
  await page.getByPlaceholder('jessie.smith@example.com').press('ArrowLeft');
  await page.getByPlaceholder('jessie.smith@example.com').press('ArrowLeft');
  await page.getByPlaceholder('jessie.smith@example.com').press('ArrowLeft');
  await page.getByPlaceholder('jessie.smith@example.com').press('ArrowLeft');
  await page.getByPlaceholder('jessie.smith@example.com').press('ArrowLeft');
  await page.getByPlaceholder('jessie.smith@example.com').press('ArrowLeft');
  await page.getByPlaceholder('jessie.smith@example.com').press('ArrowLeft');
  await page.getByPlaceholder('jessie.smith@example.com').press('ArrowLeft');
  await page.getByPlaceholder('jessie.smith@example.com').press('ArrowLeft');
  await page.getByPlaceholder('jessie.smith@example.com').press('ArrowRight');
  await page.getByPlaceholder('jessie.smith@example.com').fill('steve-test01@gmail.com');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Rallly', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Home' })).toBeVisible();
  await page.getByRole('link', { name: 'Live' }).click();
  await page.locator('div').filter({ hasText: /^Monthly MeetingLive1$/ }).getByRole('link').click();
  await expect(page.getByText('Participants11 option')).toBeVisible();
});